# Generated by Django 5.2.7 on 2025-11-04 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message_length', models.IntegerField(default=0)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_quick_response', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(blank=True, help_text='Null for channel messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to='core.developer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.developer')),
            ],
        ),
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_key', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='core.developer')),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jiraticket'),
        ),
    ]
